Repository GSM-MSG/GCMS-FrontEnd-V3, pull requests merged in 2024-10, with the labels that each got.

#9 🔀 클럽 컴포넌트 제작
  src/assets/png/testClubImg.png
  src/assets/svg/ClubStroke.tsx
  src/assets/svg/index.tsx
  src/components/Common/Club/atoms/Attendee.tsx
  src/components/Common/Club/atoms/NotionLink.tsx
  src/components/Common/Club/atoms/RecruitmentClosed.tsx
  src/components/Common/Club/atoms/RecruitmentCount.tsx
  src/components/Common/Club/molecules/ClubInfo.tsx
  src/components/Common/Club/molecules/RecruitmentStatus.tsx
  src/components/Common/Club/organisms/Club.tsx
  src/components/Common/Club/organisms/index.stories.ts
  src/components/Common/Snackbar/index.stories.ts
  src/styles/globals.css
  src/types/components/Club/club.ts
  src/types/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#12 🔀 header 반응형 추가
  src/assets/icons/club.tsx
  src/assets/icons/community.tsx
  src/assets/icons/filter.tsx
  src/assets/icons/home.tsx
  src/assets/icons/index.mdx
  src/assets/icons/index.tsx
  src/assets/icons/notice.tsx
  src/assets/icons/personRound.tsx
  src/components/Common/Header/MobileNav/index.tsx
  src/components/Common/Header/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#14 🔀 메인 페이지 제작
  next.config.mjs
  src/app/(pages)/[category]/page.tsx
  src/assets/svg/NullIcon.tsx
  src/assets/svg/index.tsx
  src/components/Common/Club/Templates/ClubList.tsx
  src/components/Common/Club/organisms/Club.tsx
  src/components/Common/Club/organisms/index.stories.ts
  src/components/Common/Header/MobileNav/index.tsx
  src/components/Common/Header/index.stories.ts
  src/components/Common/Snackbar/index.stories.ts
  src/components/Home/atoms/Alarm/Alarm.stories.tsx
  src/components/Home/atoms/Alarm/index.tsx
  src/components/Home/atoms/Navigation/Navigate.stories.tsx
  src/components/Home/atoms/Navigation/index.tsx
  src/components/Home/atoms/NullData/NullData.stories.tsx
  src/components/Home/atoms/NullData/index.tsx
  tailwind.config.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#15 🔀 내 동아리 리스트 페이지 제작
  src/app/(pages)/community/page.tsx
  src/app/(pages)/my/page.tsx
  src/app/(pages)/myClub/page.tsx
  src/app/(pages)/notice/page.tsx
  src/app/myClub/page.tsx
  src/components/Common/Club/Templates/ClubList.tsx
Labels: ✨ Feature

#11 🔀 모달, 프로필카드 컴포넌트 만들었습니다
  src/components/Alert/Modal/atoms/AttendanceCheckButtons.tsx
  src/components/Alert/Modal/atoms/Description.tsx
  src/components/Alert/Modal/atoms/Footer.tsx
  src/components/Alert/Modal/atoms/Header.tsx
  src/components/Alert/Modal/index.stories.ts
  src/components/Alert/Modal/index.tsx
  src/components/Common/UserProfileCard/index.stories.ts
  src/components/Common/UserProfileCard/index.tsx
Labels: ✨ Feature

#17 🔀 커뮤니티 글쓰기 페이지 제작
  src/app/(pages)/community/write/page.tsx
  src/components/Common/CommunityState/index.tsx
  src/components/Community/atoms/TextArea/index.stories.tsx
  src/components/Community/atoms/TextArea/index.tsx
  src/types/components/Community/textAreaType.ts
Labels: ✨ Feature

#19 🔀 공지사항 페이지 제작
  src/app/(pages)/notice/page.tsx
  src/components/Home/atoms/Alarm/index.tsx
  src/components/Notice/atoms/NoticeDetail/index.stories.tsx
  src/components/Notice/atoms/NoticeDetail/index.tsx
  src/components/Notice/atoms/NoticeListItem/index.stories.tsx
  src/components/Notice/atoms/NoticeListItem/index.tsx
  src/components/Notice/molecules/NoticeList/index.tsx
Labels: ✨ Feature

#18 🔀 .github 폴더 추가
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/todo.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙ Setting
