Repository GSM-MSG/GCMS-FrontEnd-V3, pull requests merged in 2024-09, with the labels that each got.

#1 🔀 버튼 컴포넌트 제작
  .prettierrc
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/ui/Button/button.stories.ts
  src/components/ui/Button/button.tsx
  src/components/ui/checkbox.stories.ts
  src/components/ui/checkbox.tsx
  src/shared/atoms/TestButton/index.stories.ts
  src/shared/atoms/TestButton/index.tsx
  src/shared/atoms/Text/index.stories.ts
  src/shared/atoms/Text/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#2 🔀 폴더 구조 변경
  package-lock.json
  package.json
  src/assets/icons/arrowDown.tsx
  src/assets/icons/arrowLeft.tsx
  src/assets/icons/arrowRight.tsx
  src/assets/icons/arrowUp.tsx
  src/assets/icons/circleX.tsx
  src/assets/icons/file.tsx
  src/assets/icons/index.mdx
  src/assets/icons/index.tsx
  src/assets/icons/kababMenu.tsx
  src/assets/icons/logout.tsx
  src/assets/icons/pencil.tsx
  src/assets/icons/person.tsx
  src/assets/icons/plus.tsx
  src/assets/icons/search.tsx
Labels: ⚡️ Simple

#3 🔀 스낵바 컴포넌트 제작
  src/app/page.tsx
  src/assets/icons/index.mdx
  src/assets/icons/index.tsx
  src/assets/icons/x.tsx
  src/components/Common/Snackbar/index.stories.ts
  src/components/Common/Snackbar/index.tsx
  src/components/ui/Button/index.stories.ts
  src/components/ui/Button/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#4 🔀 컴포넌트 변경사항 반영
  src/assets/icons/chat.tsx
  src/assets/icons/crown.tsx
  src/assets/icons/heart.tsx
  src/assets/icons/index.mdx
  src/assets/icons/index.tsx
  src/assets/icons/link.tsx
  src/assets/icons/linkArrow.tsx
  src/assets/icons/profile.tsx
  src/components/Common/Snackbar/index.tsx
  src/components/ui/Button/index.tsx
Labels: ⚡️ Simple

#5 🔀 textfield 컴포넌트 추가
  package-lock.json
  src/components/ui/TextField/index.stories.ts
  src/components/ui/TextField/index.tsx
Labels: ✨ Feature

#6 🔀 폰트 방식 변경
  .storybook/main.ts
  .storybook/preview.ts
  src/app/apis/index.tsx
  src/app/fonts/fonts.css
  src/app/layout.tsx
  src/app/page.tsx
  src/lib/TanstackProviders.tsx
  src/styles/fonts.ts
  src/styles/fonts/Pretendard-Black.woff2
  src/styles/fonts/Pretendard-Bold.woff2
  src/styles/fonts/Pretendard-ExtraBold.woff2
  src/styles/fonts/Pretendard-ExtraLight.woff2
  src/styles/fonts/Pretendard-Light.woff2
  src/styles/fonts/Pretendard-Medium.woff2
  src/styles/fonts/Pretendard-Regular.woff2
  src/styles/fonts/Pretendard-SemiBold.woff2
  src/styles/fonts/Pretendard-Thin.woff2
  src/styles/globals.css
Labels: ⚙ Setting, ⚡️ Simple

#7 🔀 Label 컴포넌트 추가 및 textfield 수정
  package-lock.json
  package.json
  src/components/ui/Label/index.stories.ts
  src/components/ui/Label/index.tsx
  src/components/ui/TextField/index.stories.ts
  src/components/ui/TextField/index.tsx
Labels: ✨ Feature
